### ISSUE TITLE
Included in reference list

### ISSUE THREAD

**Issue by amis92** [trampster/JsonSrcGen#35]
Hi,

I've included your repository in my personal [C# Source Generators list](https://github.com/amis92/csharp-source-generators) to help gather these kind of projects in one place and hopefully under single umbrella, thus I propose to add the `csharp-sourcegenerator` topic to this repository to help with visibility.

I hope you're okay with this. If you happen to know other generator projects, I'll be happy to enlist those in my list as well.

Thanks!

**Comment by trampster** [comment]
Thanks,

I've added the topic.

StrongInject is a source generator which does Dependency Injection. The developer helped me with some of my Source Generator questions. https://github.com/YairHalberstadt/stronginject
