### ISSUE TITLE
Support for Decimal type

### ISSUE THREAD

**Issue by WillEhrendreich** [trampster/JsonSrcGen#49]
Hello! Thank you for this awesome package!

Would it be possible to support Decimal?
If this is already possible and I just don't understand (very likely), I apologize, this is all rather new to me.

**Comment by trampster** [comment]
How thanks for you request, currently JsonSrcGen doesn't support the Decimal type.

However I think adding Decimal support is a great idea and is definitely possible.

**Comment by trampster** [comment]
There is a new release (1.1.0 Alpha 1) which has decimal support. ( Thanks to @hugobritobh who contributed it )

You can get it on nuget here: https://www.nuget.org/packages/JsonSrcGen/1.1.0-alpha.2

Be aware that this new version requires you to have a runtime dependency on JsonSrcGen.Runtime (same version https://www.nuget.org/packages/JsonSrcGen.Runtime/1.1.0-alpha.2)
